checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  php_code_coverage:
    enabled: true

build:
  nodes:
    analysis:
      environment:
        php: 7.4.12

      tests:
        override:
          - php-scrutinizer-run

build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      other:
        after_type_cast: false
