on:
  - pull_request
  - push

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }} Yii2 ${{ matrix.yii }}

    env:
      extensions: pdo, pdo_mysql
      key: cache-v1

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
        php:
          - "7.3"
          - "7.4"
          - "8.0"
        yii:
          - "2.0.27"
          - "2.0.32"
          - "^2.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Update composer
        run: composer self-update

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Install specific Yii version
        run: "composer require -w yiisoft/yii2:${{ matrix.yii }} && composer show -D"

      - name: Setup source database
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e 'CREATE DATABASE `yiitest`;'
          mysql -D yiitest -uroot -proot < tests/data/source.sql

      - name: Run tests with phpunit
        if: matrix.php != '8.0'
        run: vendor/bin/phpunit --colors=always

      - name: Run tests with phpunit
        if: matrix.php == '8.0'
        run: vendor/bin/phpunit --coverage-clover=clover.xml --colors=always

      - name: Upload code coverage scrutinizer
        if: matrix.php == '8.0'
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
