on:
  - pull_request
  - push

name: Psalm

jobs:
  analysis:
    name: Analyzing codebase with Psalm
    runs-on: "ubuntu-latest"
    env:
      php: '7.3'
      extensions: pdo, pdo_mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: none
          tools: composer:v2

      - name: Prepare files
        run: |
          cp psalm.dist.xml psalm.xml

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github
