on:
  - pull_request
  - push

name: Test

jobs:
  tests:
    name: Testing with yii2:${{ matrix.yii }}. PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-latest"
        php:
          - "7.3"
          - "8.0"
          - "latest"
        yii:
          - "2.0.27"
          - "2.0.32"
          - "current"

    env:
      extensions: pdo, pdo_mysql

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Prepare files
        run: |
          cp phpunit.dist.xml phpunit.xml

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Install specific Yii version
        if: ${{ matrix.yii != 'current' }}
        run: |
          composer remove yiisoft/yii2
          composer require --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi yiisoft/yii2:${{ matrix.yii }}

      - name: Setup source database
        env:
          MYSQL_PWD: root
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -e 'CREATE DATABASE `test`;'
          mysql -D test -uroot < tests/data/01-tables.sql
          for i in {1..5000}; do mysql -D test -uroot < tests/data/02-fill-normal.sql; done
          mysql -D test -uroot < tests/data/03-copy.sql

      - name: PHPUnit
        run: vendor/bin/phpunit --colors=always

      - uses: codecov/codecov-action@v2
        if: ${{ matrix.php == '8.1' && matrix.os == 'ubuntu-latest' && matrix.yii == 'current' }}
        with:
          files: ./tests/runtime/coverage-clover.xml
          flags: unit
          fail_ci_if_error: true
          verbose: true
